residential_complexes = [
        {name: "ЖК Солнечный Берег", type: "Кирпичный", year: 2010, country: "Россия", budget: 450, floors: 15, apartments: 200},
        {name: "Green Tower", type: "Монолитный", year: 2020, country: "США", budget: 1200, floors: 50, apartments: 400},
        {name: "ЖК Лазурный", type: "Панельный", year: 2005, country: "Казахстан", budget: 380, floors: 12, apartments: 150},
        {name: "Skyline Residence", type: "Монолитный", year: 2022, country: "Канада", budget: 900, floors: 40, apartments: 350},
        {name: "ЖК Радуга", type: "Кирпичный", year: 2015, country: "Россия", budget: 600, floors: 20, apartments: 220},
        {name: "Oceanview Towers", type: "Панельный", year: 2018, country: "Австралия", budget: 1000, floors: 35, apartments: 300},
        {name: "ЖК Светлый", type: "Блочный", year: 2024, country: "Беларусь", budget: 320, floors: 10, apartments: 120},
        {name: "Highrise Garden", type: "Монолитный", year: 2017, country: "Германия", budget: 750, floors: 30, apartments: 270},
        {name: "ЖК Южный Ветер", type: "Панельный", year: 2008, country: "Китай", budget: 500, floors: 25, apartments: 250},
        {name: "City Heights", type: "Монолитный", year: 2021, country: "Италия", budget: 820, floors: 40, apartments: 380},
        {name: "ЖК Восход", type: "Кирпичный", year: 2006, country: "Франция", budget: 340, floors: 12, apartments: 130},
        {name: "Palm Grove Residences", type: "Монолитный", year: 2019, country: "Испания", budget: 970, floors: 45, apartments: 400},
        {name: "ЖК Лесной", type: "Блочный", year: 2023, country: "Польша", budget: 310, floors: 10, apartments: 120},
        {name: "Urban Oasis", type: "Монолитный", year: 2020, country: "ОАЭ", budget: 2000, floors: 55, apartments: 450},
        {name: "ЖК Горизонт", type: "Панельный", year: 2014, country: "Чехия", budget: 600, floors: 18, apartments: 210},
        {name: "Lakeview Towers", type: "Монолитный", year: 2022, country: "Япония", budget: 1200, floors: 48, apartments: 380},
        {name: "ЖК Морской Бриз", type: "Блочный", year: 2021, country: "Турция", budget: 420, floors: 22, apartments: 240},
        {name: "Sky Horizon", type: "Монолитный", year: 2023, country: "Мексика", budget: 890, floors: 36, apartments: 300},
        {name: "ЖК Северное Сияние", type: "Панельный", year: 2016, country: "Норвегия", budget: 750, floors: 28, apartments: 280},
        {name: "Golden Tower", type: "Монолитный", year: 2024, country: "Швейцария", budget: 1300, floors: 60, apartments: 450},
        {name: "ЖК Лунный Свет", type: "Кирпичный", year: 2007, country: "Южная Корея", budget: 400, floors: 14, apartments: 180},
        {name: "Sunset Residences", type: "Монолитный", year: 2018, country: "Нидерланды", budget: 950, floors: 38, apartments: 360},
        {name: "ЖК Снежная Долина", type: "Блочный", year: 2013, country: "Швеция", budget: 530, floors: 20, apartments: 200},
        {name: "Mountain View Tower", type: "Панельный", year: 2019, country: "Австрия", budget: 1100, floors: 42, apartments: 370},
        {name: "ЖК Ясный Берег", type: "Кирпичный", year: 2011, country: "Россия", budget: 470, floors: 18, apartments: 230},
        {name: "Grand Horizon", type: "Монолитный", year: 2020, country: "Индия", budget: 980, floors: 45, apartments: 400},
        {name: "ЖК Ветер Перемен", type: "Панельный", year: 2009, country: "Канада", budget: 580, floors: 22, apartments: 250},
        {name: "Urban Skyline", type: "Монолитный", year: 2023, country: "Ирландия", budget: 800, floors: 32, apartments: 300},
        {name: "ЖК Солнечный Парк", type: "Блочный", year: 2016, country: "Аргентина", budget: 440, floors: 15, apartments: 180},
        {name: "Skyline Heights", type: "Монолитный", year: 2021, country: "Великобритания", budget: 1300, floors: 50, apartments: 420},
        {name: "ЖК Зеленый Луг", type: "Кирпичный", year: 2010, country: "Испания", budget: 480, floors: 18, apartments: 210},
        {name: "Crystal Peak", type: "Монолитный", year: 2022, country: "Сингапур", budget: 1400, floors: 60, apartments: 450},
        {name: "ЖК Летний Бриз", type: "Блочный", year: 2014, country: "Бразилия", budget: 390, floors: 13, apartments: 160},
        {name: "Sunrise Tower", type: "Монолитный", year: 2019, country: "ЮАР", budget: 920, floors: 40, apartments: 380},
        {name: "ЖК Северный Лес", type: "Панельный", year: 2005, country: "Финляндия", budget: 510, floors: 16, apartments: 190},
        {name: "Emerald Towers", type: "Монолитный", year: 2021, country: "Новая Зеландия", budget: 1200, floors: 48, apartments: 420},
        {name: "ЖК Золотая Осень", type: "Кирпичный", year: 2017, country: "Россия", budget: 430, floors: 20, apartments: 220},
        {name: "Lakeview Heights", type: "Монолитный", year: 2023, country: "Филиппины", budget: 880, floors: 36, apartments: 350},
        {name: "ЖК Алый Закат", type: "Панельный", year: 2015, country: "Чили", budget: 670, floors: 25, apartments: 280},
        {name: "Ocean Breeze Tower", type: "Монолитный", year: 2022, country: "Португалия", budget: 1500, floors: 55, apartments: 470},
        {name: "ЖК Лунный Сад", type: "Блочный", year: 2018, country: "Греция", budget: 520, floors: 17, apartments: 200},
        {name: "Golden Crest", type: "Монолитный", year: 2020, country: "Израиль", budget: 1100, floors: 46, apartments: 410},
        {name: "ЖК Лесная Гавань", type: "Панельный", year: 2008, country: "Эстония", budget: 460, floors: 19, apartments: 210},
        {name: "Sunlit Heights", type: "Монолитный", year: 2021, country: "Таиланд", budget: 1250, floors: 50, apartments: 430},
        {name: "ЖК Зимний Ветер", type: "Кирпичный", year: 2012, country: "Исландия", budget: 500, floors: 16, apartments: 200},
        {name: "Skyline Oasis", type: "Монолитный", year: 2024, country: "Индонезия", budget: 900, floors: 40, apartments: 380},
        {name: "ЖК Теплый Лес", type: "Панельный", year: 2013, country: "Швейцария", budget: 590, floors: 22, apartments: 260},
        {name: "Blue Horizon Tower", type: "Монолитный", year: 2020, country: "Южная Африка", budget: 1400, floors: 55, apartments: 470},
        {name: "ЖК Берег Неба", type: "Кирпичный", year: 2014, country: "Польша", budget: 430, floors: 18, apartments: 210},
        {name: "Sunrise Peaks", type: "Монолитный", year: 2023, country: "Колумбия", budget: 950, floors: 42, apartments: 400}
]
